### ISSUE TITLE
Can't have <BarLoader width={"100%"} />

### ISSUE THREAD

**Issue by ahhughes** [LucasBassetti/react-css-loaders#4]
Bar appears to be hard coded to use 'px' units.

**Comment by LucasBassetti** [comment]
Hi, these are the properties allowed for BarLoader:

| Name | Type | Default |
|---|---|---|
| `color` | `PropTypes.string`  | `#000` |
| `duration` | `PropTypes.number`  | `1` |
| `size` | `PropTypes.number`  | `11` |

If you want a full screen loader. I recommend you create a wrapper for that. Example:

```
<div className="full-screen-wrapper">
  <BarLoader />
</div>
```
